export const CREATE_SHORT_URL="CREATE_SHORT_URL"
export const CREATE_SHORT_URL_SUCCESS="CREATE_SHORT_URL_SUCCESS"
export const CREATE_SHORT_URL_FAILURE="CREATE_SHORT_URL_FAILURE"

export const GET_DELETE_TOKEN="GET_DELETE_TOKEN"
export const GET_DELETE_TOKEN_SUCCESS="GET_DELETE_TOKEN_SUCCESS"
export const GET_DELETE_TOKEN_FAILURE="GET_DELETE_TOKEN_FAILURE"

export const DELETE_URL="DELETE_URL"
export const DELETE_URL_SUCCESS="DELETE_URL_SUCCESS"
export const DELETE_URL_FAILURE="DELETE_URL_FAILURE"